### ISSUE TITLE
JWT AUTHENTICATION

### ISSUE THREAD

**Issue by pauloherbt** [pauloherbt/LoadingJR-PS_2024#5]
# TODO

- [x] Implementar JWT (JWT lib)
- [x] Config Spring Security
- [x] Liberar apenas POST para users e realizar login
- [ ] Tratar exceções
